'use client';
import {useEffect,useState} from 'react';
import copy from './cleanroom-copy.json';
import CleanroomPlayground from './cleanroom-playground';
const REPO='https://github.com/Ag3497120/cleanroom';
export default function CleanroomSite({base='',marketing=false,author=false}:{base?:string;marketing?:boolean;author?:boolean}){
  const [locale,setLocale]=useState('en'),[platform,setPlatform]=useState('macOS'),[copied,setCopied]=useState(false),[copyError,setCopyError]=useState('');
  const l=copy.find(x=>x.code===locale)??copy[0],ja=locale==='ja';
  useEffect(()=>{const value=new URLSearchParams(location.search).get('lang');if(value&&copy.some(x=>x.code===value))setLocale(value);},[]);
  useEffect(()=>{document.documentElement.lang=locale;},[locale]);
  const command='git clone '+REPO+'.git cleanroom\ncd cleanroom\npython3 -m venv .venv\nsource .venv/bin/activate\npython -m pip install -e ./core\nverantyx setup accounts\nverantyx';
  const copyInstall=async()=>{try{await navigator.clipboard.writeText(command);setCopied(true);setCopyError('');}catch{setCopyError(ja?'自動コピーできません。下のコマンドを選択できます。':'Copy unavailable. Select the commands below.');}};
  const authorLink=base+'/author/?lang='+locale,guide=REPO+'/blob/main/core/docs/OPERATIONS.'+locale+'.md';
  const asset=(path:string)=>base+'/cleanroom/'+path;
  const install=<section className="cr-install" id="install"><div><span className="cr-index">01 / ON YOUR COMPUTER</span><h2>{l.start}</h2><p>Python 3.11+ · macOS / Linux · Windows via WSL2</p></div><div className="cr-terminal-card"><header><div role="group" aria-label="Installation platform">{['macOS','Linux','Windows / WSL2'].map(p=><button aria-pressed={platform===p} key={p} onClick={()=>{setPlatform(p);setCopied(false);}}>{p}</button>)}</div><button className="cr-copy" onClick={()=>void copyInstall()} aria-label={ja?'インストールコマンドをコピー':'Copy install commands'} title={ja?'コマンドをコピー':'Copy commands'}><img src={asset('mark.svg')} width="30" height="30" alt=""/><span>{copied?(ja?'コピー済み':'Copied'):'Copy'}</span></button></header><pre><code>{command}</code></pre><p>{platform==='Windows / WSL2'?(ja?'先にWSL2内でPythonとGitを用意します。ネイティブWindows版の動作保証ではありません。':'Run inside WSL2 with Python and Git. This is not a native Windows compatibility claim.'):(ja?'Python 3.11以上とGitが必要です。新しいターミナルでは仮想環境を再び有効化します。':'Requires Python 3.11+ and Git. Reactivate the environment in a new terminal.')}</p><output role="status">{copyError}</output></div><p><a href={guide}>{l.read} ↗</a> · <a href={REPO}>GitHub ↗</a></p></section>;
  return <div className="cr-site" lang={locale}>
    <a className="cr-skip" href="#main">Skip to content</a>
    <nav className="cr-top"><a className="cr-small-brand" href={base+'/?lang='+locale}><img src={asset('mark.svg')} width="32" height="32" alt="Cleanroom"/>cleanroom</a><div><a href={guide}>{l.read}</a><a href={REPO}>GitHub</a><label className="cr-language"><span className="cr-sr">Language</span><select value={locale} onChange={e=>setLocale(e.target.value)}>{copy.map(x=><option key={x.code} value={x.code}>{x.name}</option>)}</select></label></div></nav>
    <main id="main">
      {author?<article className="cr-author"><span className="cr-index">THE PERSON BEHIND THE NOTEBOOK</span><h1>{l.author}</h1><h2>本西航大</h2><p>{l.origin}</p><p>{l.intro}</p><p>{ja?'これは、個人が自分の開発と将来への不安から始めたプロジェクトです。商用サービスを売るための紹介ではありません。AIに任せながらも、作るものへの愛着や、作り手としての理解を残したいと思っています。':'This began as a personal response to building with AI and worrying about the future. It is not a commercial sales pitch. I want to keep the attachment to what I make, and the understanding that lets me continue shaping it.'}</p><aside>{l.foot}</aside><a href={REPO+'/blob/main/core/docs/origins/README.md'}>{ja?'制作のきっかけと議論を読む':'Read the origins and development notes'} ↗</a></article>:<>
      <header className="cr-hero"><span className="cr-index">A NOTEBOOK FOR MAKING THINGS TOGETHER</span><img className="cr-wordmark" src={asset('logo.svg')} width="550" height="135" alt="cleanroom"/><h1>{l.tag}</h1><p>{l.intro}</p><div className="cr-hero-actions"><a className="cr-primary" href={marketing?'#install':'#play'}>{marketing?l.start:(ja?'操作を試す':'Try the workspace')}</a><a href={marketing?'https://ag3497120.github.io/cleanroom/':'https://verantyx.ai'}>{marketing?(ja?'ブラウザで体験':'Try in your browser'):(ja?'プロジェクトについて':'About the project')} ↗</a></div><span className="cr-edition">SOURCE PREVIEW · YOUR DECISIONS, YOUR PACE</span></header>
      {marketing&&install}
      {!marketing&&<section className="cr-play-section" id="play"><div className="cr-section-title"><span className="cr-index">01 / TRY THE FEEL</span><h2>{l.ops}</h2><p>{ja?'最初は通信なしの操作デモ。実AIへの依頼は、送信先を選んでから。':'Start with an offline interaction demo. Calling your own AI is a separate, explicit action.'}</p></div><CleanroomPlayground locale={locale}/><p className="cr-caption">{l.limits}</p></section>}
      {!marketing&&install}
      <section className="cr-film" id="work"><div className="cr-film-media"><video controls playsInline preload="none" poster={asset('cli-demo-poster.png')} aria-label="Recorded real CLI with scripted demo data"><source src={asset('cli-demo.mp4')} type="video/mp4"/><a href={asset('cli-demo.gif')}>View GIF</a></video><small>{ja?'実際のCLIをプログラムで操作・録画。AI出力はデモ用データ。':'Programmed recording of the real CLI. AI outputs are fixture data.'}</small></div><div><span className="cr-index">02 / WHAT IS CLEANROOM?</span><h2>{l.known}</h2><p>{l.meaning}</p><ol>{l.items.map((x,i)=><li key={x}><span>0{i+1}</span>{x}</li>)}</ol><a href={guide}>{l.read} ↗</a></div></section>
      <section className="cr-notes"><div><span className="cr-index">03 / TWO SIDES, ONE PROJECT</span><h2>{ja?'任せることと、手元に残すこと。':'A place to work. A place to keep.'}</h2></div><article><h3>Agent</h3><p>{l.request}</p><p>{l.ref}</p></article><article><h3>Owner</h3><p>{l.memo}</p><p>{l.privacy}</p></article></section>
      <section className="cr-origin"><span className="cr-index">04 / WHY I STARTED</span><h2>{ja?'作る経験まで、手放したくなかった。':'I did not want to lose the experience of making.'}</h2><p>{l.origin}</p><div><a href={authorLink}>{l.author} ↗</a><a href={REPO+'/blob/main/core/docs/origins/README.md'}>{ja?'原文と開発記':'Sources & development notes'} ↗</a></div></section>
      <section className="cr-boundary"><h3>{ja?'試せること。まだ約束しないこと。':'What you can try. What we do not promise.'}</h3><p>{l.limits}</p><p>{ja?'APIキーやサブスクトークンをサイトに保存しません。API接続は明示操作で指定先へ直接送信します。提供先の保持方針や料金は別です。実際の開発やサブスクの利用はCLIで行えます。':'This site does not persist API keys or subscription tokens. Direct API calls require explicit consent. Provider retention and billing are separate. Use the CLI for actual development and official subscription connections.'}</p><a href={REPO+'/blob/main/docs/PUBLICATION.md'}>{ja?'公開構成とプライバシー':'Publication & privacy'} ↗</a>{!marketing&&<a href={base+'/terminal/'}>{ja?'既存の計算ゲートウェイ（別サービス）':'Existing compute gateway (separate service)'} ↗</a>}</section>
      </>}
    </main>
    <footer className="cr-site-footer"><a className="cr-small-brand" href={base+'/'}><img src={asset('mark.svg')} alt="" width="32" height="32"/>cleanroom</a><p>{l.foot}</p><a href={authorLink}>{l.author}</a><a href={REPO}>GitHub</a>{marketing&&<a href="/apps/">Other projects</a>}</footer>
  </div>;
}
