export const en = {
  preview: 'Browser rehearsal', boundary: 'This tab only. No tools run. Ask your AI is a separate, explicit action.',
  play: 'Play the example', ask: 'Ask your AI', switch: 'Switch input', submit: 'Send',
  agent: 'Work & responses', owner: 'Your notebook', request: 'What shall we build?',
  placeholder: 'A request, an L-number, or the first letters of an Owner item...',
  memo: 'A note just for you', search: 'Search this notebook', empty: 'No matching notes. This is not an ability judgment.',
  controls: 'Empty Enter: Agent > Memo > Search. Shift+Enter: newline. Arrows + Tab: references.',
  scroll: 'Wheel / Page keys: active pane only. Your other pane stays in place.',
  you: 'YOU', ai: 'AI RESPONSE', system: 'ACTIVITY', local: 'Your input, in this tab only', proposal: 'AI PROPOSAL / FIXTURE',
  note: 'PRIVATE MEMO', intent: 'YOUR REQUEST', assumption: 'ASSUMPTION', unknown: 'NOT CHECKED',
  notRun: 'Recorded in this browser, not executed. Use Ask your AI for an explicit API call, or install the CLI for implementation.',
  demoRequest: 'Build an offline notes app.',
  demoPlan: 'I will separate local storage from synchronization. A recoverable copy comes first. This is scripted work, not a real implementation.',
  topic: 'Keep a recoverable copy before sync',
  insight: 'A second device can overwrite an edit. Keep the original locally, then ask the owner how conflicts should be resolved. You can revisit this next time.',
  uncertainty: 'Multi-device conflict handling has not been checked.',
  example: 'SCRIPTED EXAMPLE / NO MODEL CALLS', eta: 'Example estimate: build 2–4 min, checks 1–2 min. Not a live prediction.',
  question: 'Read-only explanation from the scripted note. The implementation example remains in place.',
  next: 'Optional. Send this L-number in Agent to open the explanation. No mastery is inferred.',
  pending: 'A choice is waiting in Agent. Your memo is not interrupted.',
  diff: 'Review the proposed change', once: 'Allow once', workspace: 'Allow in this workspace', always: 'Allow permanently', deny: 'Deny',
  diffDetail: 'Rehearsal only: no file changes or permissions are stored. The real CLI reviews candidate edits separately from adoption.',
  queue: 'Queue after the current work', steer: 'Apply at the next safe step', scheduling: 'How should this input be handled?',
  queued: 'Queued in the example. No command has executed.', steered: 'The example will use this instruction at a safe step, not during an in-flight tool.',
  finished: 'The example candidate is ready. No tests have run. Your notes and optional insight remain separate from the answer.',
  refused: 'Example change declined. No files were modified.',
  private: 'TEMPORARY CHAT', privateHelp: 'This temporary exchange is excluded from the notebook and input history. A provider call, if you choose one, has its own retention policy.',
  privateAnswer: 'This is a temporary rehearsal. Open Ask your AI to choose an endpoint explicitly; this page does not invent a model response.',
  settings: 'INLINE SETTINGS', model: 'Choose your AI connection', close: 'Close',
  settingsHelp: 'CLI: subscription, API, Ollama or LM Studio. Reasoning and context size depend on provider support. Browser: choose an endpoint in Ask your AI.',
  localOnly: 'This operation needs the local CLI. The browser does not pretend to compact history, change model permissions or open your local database.',
  newAgent: 'New Agent conversation. The Owner notebook has not been replaced.',
  guide: 'Guided rehearsal', skip: 'Leave guide', hint0: 'Agent: write a request and press Enter, or play the example.',
  hint1: 'Press Enter in an empty Agent field. The yellow Owner memo becomes active. Write a private note.',
  hint2: 'Press empty Enter again. Green means search. Type part of your note; clear it and press Enter to return.',
  hint3: 'In Agent, type the first letters of an Owner title. Use arrows and Tab to insert only that reference.',
  hint4: 'Try // followed by a question. It stays out of the notebook. Use /close to return.',
  start: 'Type verantyx to leave the guide. This browser remains a rehearsal; the installed CLI does real work.',
  guideDone: 'Guide finished. You can keep trying the controls here. Install the CLI for real project work.',
  size: 'Reading size', smaller: 'Smaller text', larger: 'Larger text', details: 'Show system activity',
  historyLimit: 'Browser preview keeps the latest 200 messages. The local CLI has a durable archive.',
  source: 'Scripted source, not evidence or a human decision', demoModel: 'Scripted fixture / no model',
  refs: 'Owner references', commands: 'Commands', installed: 'Install the local CLI', time: 'Saved',
};
export const copy: Record<string, typeof en> = {
 en,
 ja: {...en, preview:'ブラウザ操作体験', boundary:'このタブ内のみ。ツールは実行しません。AIへの送信は別途選ぶ操作です。',
 play:'例を再生', ask:'AIに頼む', switch:'入力先を切替', submit:'送信', agent:'仕事と回答', owner:'自分のノート',
 request:'何を一緒に作りますか？', placeholder:'依頼、L番号、またはOwner項目の先頭文字…', memo:'自分用に残すメモ', search:'このノートを検索',
 empty:'一致する記録はありません。能力の評価ではありません。', controls:'空Enter: Agent > メモ > 検索。Shift+Enter: 改行。矢印 + Tab: 参照。',
 scroll:'ホイール / Pageキーは入力先の側だけ。もう一方の位置は保ちます。', you:'あなた', ai:'AIの回答', system:'操作状況',
 local:'このタブ内だけの入力', proposal:'AIの提案 / デモ', note:'自分用メモ', intent:'あなたの依頼', assumption:'仮定', unknown:'未確認',
 notRun:'ブラウザに入力しただけで、未実行です。実AIへの送信は「AIに頼む」、実装はローカルCLIで行います。',
 demoRequest:'オフラインで使えるノートアプリを作って。', demoPlan:'ローカル保存と同期を分け、復元できるコピーを先に用意します。説明用の作業であり、実装を実行した結果ではありません。',
 topic:'同期の前に復元できるコピーを残す', insight:'別の端末の編集で内容が上書きされる可能性があります。原本をローカルに残し、競合の解決方針は本人に確認します。理解は次の機会でも構いません。',
 uncertainty:'複数端末での競合処理は未確認です。', example:'説明用データ / モデル呼び出しなし',
 eta:'見積もりの表示例: 実装2〜4分、検査1〜2分。実際の予測ではありません。',
 question:'保存したデモノートからの読み取り専用の説明です。元の実装例はそのまま残ります。',
 next:'任意です。L番号をAgentへ送ると説明を開けます。習得したとは判定しません。',
 pending:'Agentに選択待ちがあります。メモ入力は続けられます。', diff:'変更候補を見る', once:'一度だけ許可', workspace:'このワークスペースで許可', always:'永久に許可', deny:'拒否',
 diffDetail:'操作練習のみ。ファイルも権限も変更しません。実CLIでは候補への書き込みと本体採用は別の判断です。',
 queue:'今の仕事の後に送る', steer:'次の安全な区切りで反映', scheduling:'この入力をどう扱いますか？',
 queued:'例の待ち列へ追加しました。コマンドは実行していません。', steered:'実行中のツールへ割り込まず、次の安全な区切りで反映する例です。',
 finished:'例の変更候補ができました。検査は未実行です。メモと任意の理解候補は回答と別に残ります。',
 refused:'例の変更を拒否しました。ファイルは変更していません。', private:'一時対話',
 privateHelp:'この対話はノートと入力履歴に残しません。送信を選んだ場合、接続先の保存方針は別です。',
 privateAnswer:'一時対話の練習です。実際に話す場合は「AIに頼む」で送信先を選びます。架空のモデル回答は作りません。',
 settings:'画面内設定', model:'AIの接続を選ぶ', close:'閉じる',
 settingsHelp:'CLIではサブスク・API・Ollama・LM Studioを選べます。推論量と文脈長は接続先の対応範囲で設定します。ブラウザは「AIに頼む」から接続します。',
 localOnly:'この操作はローカルCLIで行います。ブラウザが履歴を圧縮したり、権限やローカルDBを変更したようには表示しません。',
 newAgent:'Agentの会話を新しくしました。Ownerのノートはそのままです。', guide:'操作チュートリアル', skip:'案内を終える',
 hint0:'Agentへ依頼を書いてEnter。または「例を再生」で始めます。', hint1:'空のAgentでEnter。黄色いOwnerのメモに移り、自分用の記録を書けます。',
 hint2:'もう一度空Enterで緑の検索へ。メモの一部で検索し、空にしてEnterで戻れます。',
 hint3:'AgentでOwnerの項目名の先頭文字を入力。矢印とTabで必要な参照だけ挿入します。',
 hint4:'//に続けて質問するとノートに残さない対話になります。/closeで戻ります。',
 start:'verantyxと入力すると案内を終了します。このブラウザは体験版です。実作業は導入したCLIで行います。',
 guideDone:'案内を終了しました。ここでは操作を引き続き試せます。実際の開発はCLIで行います。',
 size:'文字の大きさ', smaller:'小さくする', larger:'大きくする', details:'システム通知を表示',
 historyLimit:'ブラウザは直近200件を表示します。ローカルCLIは永続アーカイブを持ちます。',
 source:'説明用の出典。証拠や本人の決定ではありません。', demoModel:'説明用データ / モデルなし',
 refs:'Ownerの参照', commands:'コマンド', installed:'ローカルCLIを導入', time:'保存'},
 'zh-Hans': {...en, preview:'浏览器操作体验', boundary:'仅在此标签页中。不执行工具。调用 AI 需要单独确认。',
 play:'播放示例', ask:'请求我的 AI', switch:'切换输入', submit:'发送', agent:'任务与回答', owner:'我的笔记',
 request:'想一起做什么？', placeholder:'任务、L编号，或Owner条目的前几个字…', memo:'仅供自己的备忘', search:'搜索此笔记',
 empty:'没有匹配的记录。这不是能力评价。', controls:'空Enter: Agent > 备忘 > 搜索。Shift+Enter: 换行。方向键 + Tab: 引用。',
 scroll:'滚轮和翻页键只滚动当前输入侧，另一侧保持位置。', you:'你', ai:'AI回答', system:'操作状态', local:'仅此标签页中的输入',
 proposal:'AI建议 / 示例', note:'私人备忘', intent:'你的请求', assumption:'假设', unknown:'尚未确认',
 notRun:'输入已记录，但没有执行。实际调用请选择“请求我的 AI”；实现项目请使用本地CLI。',
 demoRequest:'制作一个离线笔记应用。', demoPlan:'先将本地存储与同步分离，并保留可恢复副本。这是脚本示例，不是实际实现。',
 topic:'同步前保留可恢复副本', insight:'另一台设备的编辑可能覆盖内容。先保留本地原件，再请所有者决定如何处理冲突。可以下次再理解。',
 uncertainty:'多设备冲突处理尚未验证。', example:'脚本示例 / 不调用模型', eta:'估时示例: 实现2–4分钟，检查1–2分钟。不是实时预测。',
 question:'这是根据示例笔记给出的只读解释。原任务保持不变。', next:'可选：把L编号发送给Agent以查看解释。不会自动认定已掌握。',
 pending:'Agent有待选择项。可以继续写备忘。', diff:'查看变更候选', once:'仅允许一次', workspace:'在此工作区允许', always:'永久允许', deny:'拒绝',
 diffDetail:'仅供练习，不修改文件或保存权限。本地CLI将候选写入与正式采用分开。',
 queue:'当前任务完成后排队', steer:'在下一个安全节点应用', scheduling:'如何处理这条输入？',
 queued:'已加入示例队列，没有执行命令。', steered:'在安全节点应用示例指令，不中断正在执行的工具。',
 finished:'示例候选已准备好。尚未执行测试。备忘和可选学习建议与回答分别保留。', refused:'已拒绝示例变更。没有修改文件。',
 private:'临时对话', privateHelp:'不存入笔记或输入历史。如果选择发送，服务方的保留政策另行适用。',
 privateAnswer:'这是临时对话练习。通过“请求我的 AI”明确选择连接；此页面不会编造模型回答。',
 settings:'面板内设置', model:'选择AI连接', close:'关闭',
 settingsHelp:'CLI支持订阅、API、Ollama和LM Studio。推理与上下文长度取决于提供方支持。浏览器通过“请求我的 AI”连接。',
 localOnly:'此操作需要本地CLI。浏览器不会假装压缩历史、更改权限或访问本地数据库。',
 newAgent:'已新建Agent对话。Owner笔记保持不变。', guide:'操作教程', skip:'结束教程',
 hint0:'在Agent输入请求并按Enter，或播放示例。', hint1:'在空Agent输入框按Enter，黄色Owner备忘即会激活。写一条私人笔记。',
 hint2:'再次空Enter进入绿色搜索。搜索笔记片段，清空后按Enter返回。',
 hint3:'在Agent输入Owner条目的前几个字，用方向键和Tab插入引用。',
 hint4:'尝试用//开头提问，不会写入笔记。用/close返回。',
 start:'输入verantyx结束教程。浏览器仍是操作体验，实际工作请使用已安装的CLI。',
 guideDone:'教程结束。可继续体验操作；实际项目工作请安装CLI。',
 size:'阅读字号', smaller:'缩小文字', larger:'放大文字', details:'显示系统状态', historyLimit:'浏览器保留最近200条消息。本地CLI提供持久存档。',
 source:'示例来源，不是证据或人的决定', demoModel:'脚本示例 / 无模型', refs:'Owner引用', commands:'命令', installed:'安装本地CLI', time:'保存于'},
 ko: {...en, preview:'브라우저 조작 체험', boundary:'이 탭에만 유지됩니다. 도구는 실행하지 않으며 AI 전송은 별도로 선택합니다.',
 play:'예시 재생', ask:'내 AI에 요청', switch:'입력 전환', submit:'보내기', agent:'작업과 응답', owner:'나의 노트',
 request:'무엇을 함께 만들까요?', placeholder:'요청, L번호 또는 Owner 항목의 앞 글자…', memo:'나만을 위한 메모', search:'이 노트 검색',
 empty:'일치하는 기록이 없습니다. 능력에 대한 평가는 아닙니다.', controls:'빈 Enter: Agent > 메모 > 검색. Shift+Enter: 줄바꿈. 방향키 + Tab: 참조.',
 scroll:'휠과 Page 키는 현재 입력 쪽만 스크롤합니다. 다른 쪽 위치는 유지됩니다.', you:'나', ai:'AI 응답', system:'작업 상태', local:'이 탭에만 있는 입력',
 proposal:'AI 제안 / 예시', note:'개인 메모', intent:'나의 요청', assumption:'가정', unknown:'미확인',
 notRun:'브라우저에 입력되었지만 실행되지는 않았습니다. AI 전송은 “내 AI에 요청”, 실제 구현은 로컬 CLI를 사용하세요.',
 demoRequest:'오프라인 노트 앱을 만들어 줘.', demoPlan:'로컬 저장과 동기화를 분리하고 복구할 사본을 먼저 보관합니다. 실제 구현이 아닌 대본 예시입니다.',
 topic:'동기화 전에 복구 가능한 사본 남기기', insight:'다른 기기의 편집이 내용을 덮어쓸 수 있습니다. 원본을 로컬에 남기고 충돌 해결 방침은 사용자에게 묻습니다. 다음 기회에 이해해도 됩니다.',
 uncertainty:'여러 기기의 충돌 처리는 아직 확인하지 않았습니다.', example:'대본 예시 / 모델 호출 없음', eta:'예상 표시 예: 구현 2–4분, 검사 1–2분. 실제 예측이 아닙니다.',
 question:'저장된 예시 노트를 읽어 설명합니다. 원래 구현 예시는 유지됩니다.', next:'선택 사항입니다. L번호를 Agent에 보내 설명을 여세요. 습득으로 판정하지 않습니다.',
 pending:'Agent에 선택 대기가 있습니다. 메모 작업은 계속할 수 있습니다.', diff:'변경 후보 검토', once:'한 번만 허용', workspace:'이 작업 공간에서 허용', always:'영구 허용', deny:'거부',
 diffDetail:'조작 연습으로 파일이나 권한을 바꾸지 않습니다. 실제 CLI에서는 후보 쓰기와 본체 채택을 구분합니다.',
 queue:'현재 작업 뒤에 예약', steer:'다음 안전한 단계에서 반영', scheduling:'이 입력을 어떻게 처리할까요?',
 queued:'예시 대기열에 추가했습니다. 명령은 실행하지 않았습니다.', steered:'실행 중인 도구를 방해하지 않고 다음 안전한 단계에 반영하는 예시입니다.',
 finished:'예시 후보가 준비되었습니다. 검사는 실행하지 않았습니다. 메모와 이해 제안은 응답과 별개로 남습니다.', refused:'예시 변경을 거부했습니다. 파일은 바뀌지 않았습니다.',
 private:'일시 대화', privateHelp:'노트와 입력 기록에 저장하지 않습니다. 전송을 선택하면 제공업체의 보관 정책은 별도로 적용됩니다.',
 privateAnswer:'일시 대화 연습입니다. 실제 대화는 “내 AI에 요청”에서 연결을 명시적으로 선택하세요. 모델 응답을 지어내지 않습니다.',
 settings:'화면 내 설정', model:'AI 연결 선택', close:'닫기',
 settingsHelp:'CLI는 구독, API, Ollama, LM Studio를 지원합니다. 추론량과 문맥 크기는 제공업체 지원에 따릅니다. 브라우저는 “내 AI에 요청”으로 연결합니다.',
 localOnly:'로컬 CLI가 필요한 조작입니다. 브라우저에서 기록 압축, 권한 변경, 로컬 DB 접근을 한 것처럼 표시하지 않습니다.',
 newAgent:'Agent 대화를 새로 만들었습니다. Owner 노트는 그대로입니다.', guide:'조작 안내', skip:'안내 종료',
 hint0:'Agent에 요청을 쓰고 Enter를 누르거나 예시를 재생하세요.', hint1:'빈 Agent 입력에서 Enter를 누르면 노란 Owner 메모로 이동합니다. 개인 메모를 남기세요.',
 hint2:'다시 빈 Enter를 누르면 초록 검색입니다. 메모 일부를 검색하고 비운 뒤 Enter로 돌아오세요.',
 hint3:'Agent에 Owner 항목의 앞 글자를 입력하고 방향키와 Tab으로 참조를 넣으세요.',
 hint4:'// 다음에 질문하면 노트에 남기지 않습니다. /close로 돌아오세요.',
 start:'verantyx를 입력하면 안내가 끝납니다. 이 브라우저는 체험판이며 실제 작업은 설치한 CLI에서 합니다.',
 guideDone:'안내를 마쳤습니다. 계속 조작을 체험하거나 실제 작업을 위해 CLI를 설치하세요.',
 size:'글자 크기', smaller:'작게', larger:'크게', details:'시스템 상태 표시', historyLimit:'브라우저는 최근 200개 메시지만 유지합니다. 로컬 CLI는 영구 보관함을 제공합니다.',
 source:'대본 출처이며 증거나 사람의 결정이 아닙니다.', demoModel:'대본 예시 / 모델 없음', refs:'Owner 참조', commands:'명령', installed:'로컬 CLI 설치', time:'저장'},
 es: {...en, preview:'Ensayo en el navegador', boundary:'Solo en esta pestaña. No ejecuta herramientas. Pedir a tu IA es una acción aparte y explícita.',
 play:'Reproducir ejemplo', ask:'Pedir a mi IA', switch:'Cambiar entrada', submit:'Enviar', agent:'Trabajo y respuestas', owner:'Tu cuaderno',
 request:'¿Qué creamos?', placeholder:'Una petición, un número L o las primeras letras de una nota…', memo:'Una nota para ti', search:'Buscar en este cuaderno',
 empty:'No hay notas coincidentes. No es una evaluación de capacidad.', controls:'Enter vacío: Agent > Nota > Buscar. Shift+Enter: nueva línea. Flechas + Tab: referencias.',
 scroll:'Rueda / teclas Page: solo el panel activo. El otro conserva su posición.',
 you:'TÚ', ai:'RESPUESTA DE IA', system:'ACTIVIDAD', local:'Tu entrada, solo en esta pestaña', proposal:'PROPUESTA DE IA / EJEMPLO',
 note:'NOTA PRIVADA', intent:'TU PETICIÓN', assumption:'SUPOSICIÓN', unknown:'SIN COMPROBAR',
 notRun:'Registrado en el navegador, no ejecutado. Usa Pedir a mi IA para una llamada explícita, o instala la CLI para implementar.',
 demoRequest:'Crea una aplicación de notas sin conexión.', demoPlan:'Separaré el almacenamiento local de la sincronización. Primero, una copia recuperable. Es un guion, no una implementación real.',
 topic:'Conservar una copia antes de sincronizar', insight:'Una edición de otro dispositivo puede sobrescribir datos. Conserva el original local y pregunta al propietario cómo resolver conflictos. Puedes retomarlo la próxima vez.',
 uncertainty:'Los conflictos entre dispositivos no se han comprobado.', example:'EJEMPLO CON GUION / SIN LLAMADAS A MODELOS',
 eta:'Estimación de ejemplo: implementación 2–4 min, pruebas 1–2 min. No es una predicción real.',
 question:'Explicación de solo lectura a partir de la nota de ejemplo. El trabajo original se conserva.',
 next:'Opcional. Envía el número L en Agent para abrir la explicación. No implica dominio.',
 pending:'Hay una elección pendiente en Agent. Puedes seguir escribiendo tu nota.',
 diff:'Revisar el cambio propuesto', once:'Permitir una vez', workspace:'Permitir en este espacio', always:'Permitir permanentemente', deny:'Rechazar',
 diffDetail:'Solo ensayo: no modifica archivos ni guarda permisos. La CLI real separa la escritura de candidatos de su adopción.',
 queue:'Poner en cola tras el trabajo actual', steer:'Aplicar en el próximo paso seguro', scheduling:'¿Cómo se trata esta entrada?',
 queued:'En la cola del ejemplo. No se ha ejecutado ningún comando.', steered:'Se aplicará en un paso seguro del ejemplo, sin interrumpir una herramienta en curso.',
 finished:'El candidato de ejemplo está listo. No se han ejecutado pruebas. Tus notas y sugerencias opcionales permanecen separadas de la respuesta.',
 refused:'Cambio de ejemplo rechazado. No se modificaron archivos.', private:'CONVERSACIÓN TEMPORAL',
 privateHelp:'Se excluye del cuaderno y del historial de entrada. Si eliges enviar, la retención del proveedor se aplica por separado.',
 privateAnswer:'Es un ensayo temporal. Elige un destino explícito con Pedir a mi IA; esta página no inventa respuestas de modelos.',
 settings:'AJUSTES EN EL PANEL', model:'Elegir conexión de IA', close:'Cerrar',
 settingsHelp:'CLI: suscripción, API, Ollama o LM Studio. Razonamiento y contexto dependen del proveedor. Navegador: elige un destino con Pedir a mi IA.',
 localOnly:'Esta acción necesita la CLI local. El navegador no finge compactar el historial, cambiar permisos ni acceder a tu base de datos.',
 newAgent:'Nueva conversación Agent. El cuaderno Owner no ha cambiado.', guide:'Ensayo guiado', skip:'Salir de la guía',
 hint0:'Escribe una petición en Agent y pulsa Enter, o reproduce el ejemplo.',
 hint1:'Pulsa Enter en Agent vacío. Se activa la nota amarilla de Owner. Escribe una nota privada.',
 hint2:'Otro Enter vacío abre la búsqueda verde. Busca una parte de la nota; borra y pulsa Enter para volver.',
 hint3:'En Agent escribe las primeras letras de un título de Owner. Usa flechas y Tab para insertar solo esa referencia.',
 hint4:'Prueba // seguido de una pregunta. No se añade al cuaderno. Usa /close para volver.',
 start:'Escribe verantyx para salir de la guía. El navegador sigue siendo un ensayo; la CLI instalada realiza el trabajo.',
 guideDone:'Guía terminada. Puedes seguir probando los controles. Instala la CLI para trabajar en tu proyecto.',
 size:'Tamaño de lectura', smaller:'Texto menor', larger:'Texto mayor', details:'Mostrar actividad del sistema',
 historyLimit:'La vista del navegador conserva los últimos 200 mensajes. La CLI tiene un archivo duradero.',
 source:'Fuente con guion, no evidencia ni decisión humana', demoModel:'Ejemplo con guion / sin modelo', refs:'Referencias de Owner',
 commands:'Comandos', installed:'Instalar la CLI local', time:'Guardado'},
};
